source 'https://github.com/CocoaPods/Specs.git'

 plugin 'cocoapods-binary'
platform :ios, '11.2'
use_frameworks!
inhibit_all_warnings!
keep_source_code_for_prebuilt_frameworks!
#all_binary!

target 'demo' do
  # RxSwift

  pod "AFNetworking/Security"
  pod "MBKCoreAudioPlayer", :git => '/Users/lea/byte/test/MBKCoreAudioPlayer'

  # # Firebase
  # pod 'Firebase/Core', :binary => true
  # pod 'Firebase/Firestore' 
